Repository hzz4343/Community-Support-Tracker, pull requests merged in 2024-12, with the labels that each got.

#24 Volunteer hours tracker component 2
  WORK_CONSULTED.md
  styles.css
  volunteer-hours-tracker/tests/volunteer-hours-tracker-script.test.js
  volunteer-hours-tracker/volunteer-hours-tracker-script.js
  volunteer-hours-tracker/volunteer-hours-tracker.html
Labels: documentation, enhancement

#25 Update styles.css to arrage delete button
  styles.css
Labels: bug

#27 Update junit.xml with three members tests
  test-results/jest/junit.xml
Labels: enhancement

#28 Update hamburger nav
  donation-tracker/donation-tracker.html
  event-signup/event-signup.html
  index.html
  styles.css
  test-results/jest/junit.xml
  volunteer-hours-tracker/volunteer-hours-tracker.html
Labels: enhancement

#29 Update describe for simplify mockdata code
  test-results/jest/junit.xml
  volunteer-hours-tracker/tests/volunteer-hours-tracker-script.test.js
Labels: enhancement

#30 Event signup component 2: localStorage implementation and Jest testing.
  event-signup/event-signup-script.js
  event-signup/event-signup.html
  event-signup/tests/event-signup-script.test.js
Labels: bug, enhancement
