Repository hzz4343/Community-Support-Tracker, pull requests merged in 2024-11, with the labels that each got.

#12 Volunteer hours tracker component 1
  STYLE_GUIDE.md.md
  WORK_CONSULTED.md
  index.html
  package-lock.json
  package.json
  volunteer-hours-tracker/tests/volunteer-hours-tracker-script.test.js
  volunteer-hours-tracker/volunteer-hours-tracker-script.js
  volunteer-hours-tracker/volunteer-hours-tracker-styles.css
  volunteer-hours-tracker/volunteer-hours-tracker.html
Labels: enhancement

#14 Volunteer hours tracker component 1
  STYLE_GUIDE.md.md
  volunteer-hours-tracker/volunteer-hours-tracker.html
Labels: documentation, enhancement

#16 Update STYLE_GUIDE.md and index.html with google font
  STYLE_GUIDE.md
  index.html
Labels: documentation, enhancement

#17 Event signup component 1
  event-signup/event-signup-script.js
  event-signup/event-signup.html
  event-signup/tests/event-signup-script.test.js
Labels: enhancement

#18 Updated index.html - Changed links in <nav> to be relative
  index.html
Labels: bug

#20 Reverted back to absolute but prefixed with /Community-Support-Tracker/
  donation-tracker/donation-tracker.html
  event-signup/event-signup.html
  index.html
  volunteer-hours-tracker/volunteer-hours-tracker.html
Labels: bug

#19 Update google font for donation & Removed star stylesheet for event $ duplication css for styles.css
  README.md
  donation-tracker/donation-tracker.html
  event-signup/event-signup.html
  styles.css
Labels: documentation

#22 Update STYLE_GUIDE.md for seperating section
  STYLE_GUIDE.md
Labels: documentation
